// Local, shared fonts for Astro and the standalone tools. Rebuilt from the lockfile.
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, basename, join } from 'node:path';

const packages = [
  ['@fontsource-variable/inter', ['index.css']],
  ['@fontsource-variable/source-serif-4', ['index.css', 'wght-italic.css']],
  ['@fontsource/ibm-plex-mono', ['400.css', '500.css', '600.css']],
];
await mkdir('public/fonts', { recursive: true });
const faces = [];
const siteFaces = [];
for (const [pkg, styles] of packages) {
  const root = join('node_modules', pkg);
  await copyFile(join(root, 'LICENSE'), `public/fonts/${basename(pkg)}-LICENSE.txt`);
  for (const style of styles) {
    const css = await readFile(join(root, style), 'utf8');
    for (const match of css.matchAll(/@font-face\s*\{[^}]+\}/g)) {
      let face = match[0];
      const source = face.match(/url\(([^)]+\.woff2)\)/)?.[1];
      // Spanish, English and scientific Greek. Preserve the supplied Unicode ranges.
      if (!source || !/-(latin|latin-ext|greek|greek-ext)-/.test(source)) continue;
      const bytes = await readFile(join(root, source));
      const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 12);
      const name = basename(source).replace('.woff2', `.${hash}.woff2`);
      await writeFile(`public/fonts/${name}`, bytes);
      face = face.replace(/src:[^;]+;/, `src: url('/fonts/${name}') format('woff2');`);
      // Astro keeps its existing family names and weights. Virology also needs
      // real serif italics and the 600 mono weight; both share the same binaries.
      if (style === 'index.css' || style === '400.css' || style === '500.css') siteFaces.push(face);
      faces.push(face.replace(' Variable', ''));
    }
  }
}
const output = '/* Generated by scripts/prepare-fonts.mjs. */\n' + faces.join('\n') + '\n';
await writeFile('public/fonts/fonts.css', output);
await mkdir(dirname('src/styles/fonts.css'), { recursive: true });
await writeFile('src/styles/fonts.css', '/* Generated by scripts/prepare-fonts.mjs. */\n' + siteFaces.join('\n') + '\n');
console.log(`Prepared ${faces.length} local font faces (shared by site and tools).`);
